schema_version = "1.0.0"

id = "auto_dark_mode"
version = "2.0.0"
name = "Auto Dark Mode"
tagline = "Automatically follow the system light/dark mode"
maintainer = "Dale Price"
type = "add-on"

website = "https://github.com/daprice/Blender-Auto-Dark-Mode"

tags = ["System", "User Interface"]

blender_version_min = "4.0.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/advanced/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
  "2021-2024 Dale Price",
]

[permissions]
files = "Read installed themes"